### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by waderyan** [nodesource/vs-code-for-node-js-development-pack#1]
I work on VS Code and I want to feature this extension on the Marketplace. Can you add an icon?

**Comment by bnb** [comment]
@waderyan Yes, I'll see what we can do 👍

**Comment by waderyan** [comment]
Sounds great! Please let me know.

**Comment by bnb** [comment]
@waderyan I've added the icon 👍

**Comment by waderyan** [comment]
Great! Update should happen later this week.
