### ISSUE TITLE
Azure Functions Tools has been deprecated

### ISSUE THREAD

**Issue by stonehippo** [nodesource/vs-code-for-node-js-development-pack#3]
As of 2/6/18, the dependency [Azure Function Tools]() has been deprecated in favor of [Azure Functions](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions).

**Comment by bnb** [comment]
Hey there @stonehippo 👋

Just wanted to let you know that I've fixed this in the extension pack locally, but am having an issue with the NodeSource PAT - trying to work with someone at Microsoft to get it resolved.

I'll close this as soon as it's shipped! 🙏

**Comment by bnb** [comment]
Shipped in v1.2.0! 🎊 

Thanks for letting me know @stonehippo – and apologies for the _long_ delay!
